name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: postgres
        postgresql user: postgres
        postgresql password: postgres
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true
        NOTION_TOKEN: faketoken
        NOTION_JOBS_DATABASE_ID: fakedatabaseid
        PEP_DATABASE_ID: fakepepdatabaseid
        PEP_ENDPOINT: fakepependpoint
        FEATURE_FLAG_FETCH_PEP_JOBS: false
        CRON_IMPORT_ALL: false

