nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "@prisma/client@*":
    dependencies:
      ".prisma": 'link:See "resolution" field of package.json'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
