version: '3'
services:
    database:
        image: postgres:14
        environment:
            POSTGRES_USER: metiersnum
            POSTGRES_PASSWORD: metiersnum
        ports:
            - "5432:5432"

    adminer:
        image: adminer
        depends_on:
            - database
        ports:
            - 8080:8080
        restart: unless-stopped
