name: Check

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Lint
        run: yarn test:lint --ignore-pattern '/__tests__/*'

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Test (Unit)
        run: yarn test:unit

  # e2e:
  #   name: E2E Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2.5.0
  #       with:
  #         cache: yarn
  #         node-version: 16
  #     - name: Setup PostgreSQL
  #       uses: Harmon758/postgresql-action@v1.0.0
  #       with:
  #         postgresql db: postgres
  #         postgresql user: postgres
  #         postgresql password: postgres
  #     - name: Install
  #       run: yarn
  #     - name: Build
  #       run: yarn build
  #     - name: Test (E2E)
  #       run: yarn test:integration
  #       env:
  #         CI: true
  #         NOTION_TOKEN: faketoken
  #         NOTION_JOBS_DATABASE_ID: fakedatabaseid
  #         NOTION_PEP_JOBS_DATABASE_ID: fakepepdatabaseid
  #         PEP_ENDPOINT: fakepependpoint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
